---
title: "Script for GIS final"
author: "Hongjing Xiao"
date: "2021/1/11"
output: html_document
---


## Part 1: Get the data and set up a ppp object for analysis.

```{r message=FALSE, warning=FALSE}
library(spatstat)
library(here)
library(sp)
library(rgeos)
library(maptools)
library(GISTools)
library(tmap)
library(sf)
library(geojson)
library(geojsonio)
library(tmaptools)

##Get Boundaries
DTboundary <- st_read("C:/Users/ad1066/Desktop/cw/City_of_Detroit_Boundary-shp")%>%
  st_transform(., 3857)


##Get the location of all sites in the City
Sites <- st_read("C:/Users/ad1066/Desktop/cw/Low_Income_Housing_Tax_Credit_Sites_2015-shp")%>%
  st_transform(.,3857)
  

#remove duplicates
library(tidyverse)
library(sf)

Sites <- distinct(Sites)
SitesSub <- Sites[DTboundary,]

#check 
tmap_mode("view")
tm_shape(DTboundary) +
  tm_polygons(col = NA, alpha = 0.5) +
  tm_shape(SitesSub) +
  tm_dots(col = "blue")

#Set a window on DTboundary
window <- as.owin(DTboundary)
plot(window)

#create ppp object
SitesSub<- SitesSub %>%
  as(., 'Spatial')

SitesSub.ppp <- ppp(x=SitesSub@coords[,1],
                    y=SitesSub@coords[,2],
                    window=window)
SitesSub@coords[,1]

SitesSub.ppp %>%
  plot(.,pch=16,cex=0.5, 
       main="DT sites")
```


## Part 2: Kernal Density, Ripley's K and DBSCAN, then creat convex hull for clusters.
        
```{r message=FALSE, warning=FALSE}
##Analysis
#Kernal Density
SitesSub.ppp %>%
  density(., sigma=1000) %>%
  plot()

##Ripley’s K
K <- SitesSub.ppp %>%
  Kest(., correction="border") %>%
  plot()

##DBSCAN
library(raster)
library(fpc)
st_geometry(DTboundary)

#extract points from the spatial points data frame
SitesSubPoints <- SitesSub %>%
  coordinates(.)%>%
  as.data.frame()

#run the analysis
db <- SitesSubPoints %>%
  fpc::dbscan(.,eps = 2500, MinPts = 20)
plot(db, SitesSubPoints, main = "DBSCAN Output", frame = F)
plot(DTboundary$geometry, add=T)

#add info
library(ggplot2)
db
db$cluster
SitesSubPoints<- SitesSubPoints %>%
  mutate(cluster=db$cluster)
library(tidyverse)

#convex hull polygons
chulls<- SitesSubPoints %>%
  group_by(cluster) %>%
  nest() %>% 
  mutate(hull= map(data,~with(.x,chull(coords.x1,coords.x2))),
         out = map2(data, hull, ~ .x[.y,,drop=FALSE]))%>%
  dplyr::select(-data) %>%
  unnest()

#drop 0 from the dataframe
chulls <- chulls %>%
  filter(cluster >=1)

#create a ggplot2 object from the data
dbplot <- ggplot(data=SitesSubPoints, 
                 aes(coords.x1,coords.x2, colour=cluster, fill=cluster)) 
#add points 
dbplot <- dbplot + geom_point()
#add convex hulls
dbplot <- dbplot + geom_polygon(data = chulls, 
                                aes(coords.x1,coords.x2, group=cluster), 
                                alpha = 0.5) 
#plot 
dbplot + theme_bw() + coord_equal()
```


## Part 3: Add basemap to the final result.

```{r message=FALSE, warning=FALSE}
##Add bsaemap
#Get the bbox in lat long for DT
DTboundaryWGSbb <- DTboundary %>%
  st_transform(., 4326)%>%
  st_bbox()

library(OpenStreetMap)

basemap <- OpenStreetMap::openmap(c(42.3,-83.3),c(42.5,-82.9),
                                  zoom=NULL,
                                  "esri-topo")

# convert the basemap to Mercator 
basemap_bng <- openproj(basemap, projection="+init=epsg:3857")
library(ggspatial)
library(ggsn)
#plot clusters with basemap
autoplot.OpenStreetMap(basemap_bng) + 
  geom_point(data=SitesSubPoints, 
             aes(coords.x1,coords.x2, 
                 colour=cluster, 
                 fill=cluster)) + 
  geom_polygon(data = chulls, 
               aes(coords.x1,coords.x2, 
                   group=cluster,
                   fill=cluster), 
               alpha = 0.5)+
  coord_sf(crs = 3857)+
  annotation_north_arrow(which_north = "true",
                         location="tl")+
  annotation_scale(location="tr")
```

